import ICar from "src/car/ICar";
import { CarRecordInput } from "src/car/car_dto";

const cars_records: CarRecordInput[] = [
    {
        "title": "SPEEDTAIL",
        "description": "Maximum Speed: 403km/h (250mph), 0-100kph (62mph): 3.0 seconds, 0-200kph (124mph): 6.6 seconds, Maximum Power: 1036 Horsepower, Maximum Torque: 1150 Nm, Engine: V8, 4.0L with eMotor, Technology: Twin-Turbocharged V8 Engine with a parallel hybrid system, Breaking (100-0 Km/h): 32 meters, Breaking (200-0 Km/h): 132 meters, Dry Weight: 1,499kg, Kerb Weight: 1,597 kg",
        "year": 2021,
        "mileage": 0,
        "exterior_colour": "WHITE",
        "interior_colour": "DARK",
        "driver_position": "RWD",
        "engine": "4.0L V-8 Twin-Turbocharged Engine + eMotor",
        "body_type": "Coupe",
        "transmission": "7 Speed Automatic Transmission",
        "price": 13999000,
        "featured": true,
        "car_id": "FM-1010",
        "doors": 2,
        "power": 1036,
        "torque": 1150,
        "specification": "EUROPEAN",
        "top_speed": 400,
        "zero_to_100": 3,
        "more_info": "Introducing the McLaren Speedtail, a stunning and revolutionary hypercar that blends breathtaking performance, unrivaled luxury, and extraordinary innovation. The Speedtail's sleek and aerodynamic design is a testament to the pinnacle of automotive engineering and design, pushing new boundaries in both form and function. With a powerful hybrid powertrain delivering an astonishing 1070PS, the Speedtail is the fastest McLaren to date. However, it's not just a fast car - it's a true work of art, featuring bespoke materials and textures that offer unparalleled levels of personalization. Whether you're a speed enthusiast or a design aficionado, the McLaren Speedtail is the ultimate hypercar that will leave you in awe. The company's vision was to create something truly exceptional, and they have accomplished this by producing only 106 bespoke hybrid hyper-GT cars. This limited number has allowed the company to push the boundaries of innovation, exploring materials and textures that have never before been utilized in the automotive industry. The result is a car that is as rare as it is revolutionary, embodying the company's commitment to unparalleled luxury, performance, and design. Introducing the McLaren Speedtail, a stunning and revolutionary hypercar that blends breathtaking performance, unrivaled luxury, and extraordinary innovation. The Speedtail's sleek and aerodynamic design is a testament to the pinnacle of automotive engineering and design, pushing new boundaries in both form and function. With a powerful hybrid powertrain delivering an astonishing 1070PS, the Speedtail is the fastest McLaren to date. However, it's not just a fast car - it's a true work of art, featuring bespoke materials and textures that offer unparalleled levels of personalization. Whether you're a speed enthusiast or a design aficionado, the McLaren Speedtail is the ultimate hypercar that will leave you in awe. The company's vision was to create something truly exceptional, and they have accomplished this by producing only 106 bespoke hybrid hyper-GT cars. This limited number has allowed the company to push the boundaries of innovation, exploring materials and textures that have never before been utilized in the automotive industry. The result is a car that is as rare as it is revolutionary, embodying the company's commitment to unparalleled luxury, performance, and design.",
        "ask_price": false,
        "images": [
            { link: "large_23_4bdb9edb62.jpg" },
            { link: "large_22_339b5f57b8.jpg" },
            { link: "large_21_6da79306de.jpg" },
            { link: "large_20_69a3602948.jpg" },
            { link: "large_19_dfd32589a5.jpg" },
            { link: "large_18_eb4a04860c.jpg" },
            { link: "large_17_8271079b64.jpg" },
            { link: "large_16_8aeffa8820.jpg" },
            { link: "large_15_f96e6c06bc.jpg" },
            { link: "large_14_a5025b7e63.jpg" },
            { link: "large_13_0fd7f983f7.jpg" },
            { link: "large_12_cb91cc2870.jpg" },
            { link: "large_11_0dac9d6d1c.jpg" },
            { link: "large_10_a118129a62.jpg" },
            { link: "large_9_a70e922321.jpg" },
            { link: "large_8_eca05e1513.jpg" },
            { link: "large_7_3bbcc68376.jpg" },
            { link: "large_6_f676979607.jpg" },
            { link: "large_5_ffb61f703c.jpg" },
            { link: "large_4_c6b5e4d16e.jpg" },
            { link: "large_3_e3e1cdd6d9.jpg" },
            { link: "large_2_1ba7afee87.jpg" }
        ],
        "car_brand": "MCLAREN",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_eff205d96f.jpg' }
    },
    {
        "title": "Benz AMG ONE",
        "description": "Maximum Power: 1063 Horsepower, Maximum Speed: 352 KM/H, 0-100 Km/h: approximately 2.9 s, 0-200 Km/h: approximately 7 s, 0-300 Km/h: approximately 15.6 s, Dry Weight: 1695 kg, Overall width: 2.010 m, Overall length: 4.750 m, Height: 1.260 m,Wheelbase: 2,720 m",
        "year": 2024,
        "mileage": 0,
        "exterior_colour": "Black ",
        "interior_colour": "Black ",
        "driver_position": "All Wheel Drive",
        "engine": "1.6L V6 Twin-Turbocharged + 4 Electric Motors",
        "body_type": "Coupe",
        "transmission": "7-Speed Automated Manual Gearbox ",
        "price": 0,
        "featured": true,
        "car_id": "FM-1020",
        "doors": 2,
        "power": 1063,
        "torque": 0,
        "specification": "",
        "top_speed": 352,
        "zero_to_100": 2.9,
        "more_info": "Limited to just 275 units worldwide, the Mercedes-Benz AMG ONE is a truly exceptional hypercar that brings the thrill of Formula One racing to the streets. With its E PERFORMANCE hybrid drive and cutting-edge motorsport technology, the ONE is capable of delivering an unparalleled driving experience. At the heart of the ONE is a complex hybrid powertrain that combines a 1.6-liter turbocharged V6 engine with four electric motors. The result is a staggering 1,063 horsepower, propelling the ONE from 0 to 60 mph in just 2.9 seconds and on to a top speed of over 217 mph. Carbon Fiber Monocoque for Maximum Strength and Agility The ONE's carbon-fiber monocoque provides a lightweight and incredibly rigid structure, ensuring exceptional handling and cornering performance. The carbon-fiber body panels further enhance the car's aerodynamic efficiency, reducing drag and improving downforce. Active Aerodynamics for Optimal Performance The ONE's active aerodynamics system adjusts the car's front and rear wings in real time, optimizing downforce and reducing drag based on driving conditions. This system helps the ONE achieve maximum performance on the track and enhanced stability on the road. Push-Rod Suspension for Comfortable and Precise Handling The ONE's sophisticated push-rod suspension system provides a comfortable ride on the road while delivering precise handling on the track. The system uses adaptive dampers that adjust the suspension's firmness based on driving conditions. Six Drive Programs for Versatility The ONE offers six drive programs that allow drivers to tailor the car's performance to their needs. These programs range from purely electric driving for urban environments to full-fledged race mode for the track. Formula One-Inspired Interior The ONE's interior is designed to evoke the feeling of driving a Formula One car. The cockpit is minimalist and functional, with all controls within easy reach. The seats are deeply bolstered and provide excellent support for spirited driving. Limited Availability and High Demand With only 275 units produced, the Mercedes-Benz AMG ONE is a highly sought-after vehicle. Demand for the ONE far exceeds supply, making it one of the most exclusive hypercars in the world. Overall, the Mercedes-Benz AMG ONE is a true engineering marvel that represents the pinnacle of automotive performance. With its cutting-edge technology, exceptional performance, and limited availability, the ONE is sure to become a legend among car enthusiasts.",
        "ask_price": true,
        "images": [
            { link: "large_111_28d2046793.webp" },
            { link: "large_2_663a5955d0.webp" },
            { link: "large_7_301fbb978e.webp" },
            { link: "large_13_c21b22db59.webp" },
            { link: "large_18_b7bc13ad1d.webp" },
            { link: "large_11_97808f38b3.webp" },
            { link: "large_3_f06a1ebcfa.webp" },
            { link: "large_9_74064c2bb3.webp" },
            { link: "large_5_5f8a6c54b5.webp" },
            { link: "large_14_53fdf64812.webp" },
            { link: "large_6_627bf3f6fb.webp" },
            { link: "large_4_ff58e5e5e4.webp" },
            { link: "large_10_860355f2dd.webp" },
            { link: "large_15_c9ae22e8df.webp" },
            { link: "large_8_b7aae71008.webp" },
            { link: "large_16_edc7466cf7.webp" },
            { link: "large_17_a4adb92cc1.webp" },
            { link: "large_21_e3cdceadfc.webp" },
            { link: "large_22_d4faa3403a.webp" },
            { link: "large_23_21a2ec38aa.webp" },
            { link: "large_19_ca808e49b2.webp" },
            { link: "large_25_a5e2d8a3fa.webp" },
            { link: "large_20_ea387766fd.webp" },
            { link: "large_24_753aa3e967.webp" },
            { link: "large_26_fc76f27670.webp" },
            { link: "large_28_d0034fe59c.webp" },
            { link: "large_30_ecb136d9a3.webp" },
            { link: "large_27_04d15455f4.webp" }
        ],
        "car_brand": "Mercedes Benz",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_922214c3bb.jpg' }
    },
    {
        "title": "Sián Roadster ",
        "description": "Maximum Power: 819 Horsepower, Maximum Torque: 755 Nm, Maximum Speed: 350 KM/H, 0-100 Km/h (62mph): approximately 2.9 s, Dry Weight: 1645 kg, Overall width: 2.265 m, Overall length: 4.979 m, Height: 1.158 m, Wheelbase: 2.700 m",
        "year": 2021,
        "mileage": 0,
        "exterior_colour": "Nero Aldebaran",
        "interior_colour": "Black ",
        "driver_position": "All Wheel Drive",
        "engine": " 6.5L V-12 Naturally Aspirated Engine + eMotor",
        "body_type": "Hard Top Convertible ",
        "transmission": "7 Speed Automatic Transmission",
        "price": 17499000,
        "featured": true,
        "car_id": "FM-1925",
        "doors": 2,
        "power": 819,
        "torque": 755,
        "specification": "European ",
        "top_speed": 350,
        "zero_to_100": 2.9,
        "more_info": "The 2021 Lamborghini Sian Roadster is an automotive masterpiece, representing the pinnacle of Lamborghini's innovation and craftsmanship. It stands as one of the most exclusive and limited-production supercars in the world, with only 19 units produced. What sets this particular Sian Roadster apart is that it is the only fully black color SIAN Roadster in the world. This exclusive color choice not only adds to its rarity but also enhances its aesthetic appeal, making it a true collector's dream. The Sian Roadster features a naturally aspirated 6.5-liter V12 engine, capable of producing a staggering 785 horsepower. But what truly sets it apart is the addition of a 48-volt mild-hybrid system that incorporates an electric motor. This electric motor provides an extra 34 horsepower, resulting in a combined power output of 819 horsepower. The electric motor is powered by a supercapacitor, which is more advanced and faster at storing and releasing energy compared to traditional lithium-ion batteries. The Sian Roadster is not just a work of art; it's a high-performance marvel. Beneath its striking exterior, it features a state-of-the-art chassis, including a carbon fiber monocoque with aluminum front and rear frames. This construction approach ensures the perfect balance between lightweight design and structural integrity, which is crucial for achieving the car's astounding performance. The wheels are paired with P Zero Corsa tires. This combination offers superb grip and handling, allowing the Sian Roadster to hug the road in every curve and provide a thrilling driving experience. Braking performance in the Sian Roadster is equally impressive, with a dual hydraulic circuit brake system featuring a vacuum brake booster. The car has Carbon Ceramic Brakes (CCB) on both the front and rear axles, with 6-cylinder brake calipers in the front and 4-cylinder brake calipers in the rear. These high-performance brakes ensure precise and responsive stopping power, a critical component for a car capable of reaching such high speeds. The interior of the Sian Roadster is a blend of luxury and high performance. It features premium materials, including carbon fiber and Alcantara, creating a sophisticated yet sporty ambiance. The cockpit is driver-focused, with intuitive controls and a digital instrument cluster providing essential information at a glance. In conclusion, the 2021 Lamborghini Sian Roadster is a rare and extraordinary masterpiece that combines cutting-edge technology with breathtaking design. Its exclusivity, distinctive fully black finish, and exceptional performance capabilities make it a standout addition to Lamborghini's storied history.",
        "ask_price": false,
        "images": [
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_26_d72a86265c.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_37_92d289bb39.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_19_2ba23f1a15.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_8_688c29e2bb.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_32_a48504f152.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_18_069be83bff.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_29_0b62bf11b9.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_22_8294ce0eef.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_21_64f1530bdb.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_33_e9e2ca5323.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_38_2827fa8a6a.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_39_afa1a2b29f.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_12_bf6a21a7ab.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_24_7fe5b1fde6.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_4_a9046f97a9.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_3_5d3f794b0d.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_23_efca5984a5.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_10_3c7d5303f3.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_1_cdec77e8d3.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_31_f4c217d983.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_40_22de6688be.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_13_87f978a524.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_25_48745d66dd.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_11_9430181c4d.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_20_e2c2863b5f.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_9_d69acc3e33.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_16_4560de26a5.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_27_9e3aa9c435.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_28_9f216edfad.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_14_9a88389bcf.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_30_8bd87b2699.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_35_ce2d12f957.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_17_56fceee40a.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_15_a85e7eb46a.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_34_ce62289168.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_36_c72f07897d.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_5_b1efb63f40.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_6_4cbb22d73e.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_2_62a7ac7736.webp" },
            { link: "large_Lamborghini_Sian_Roadster_F1rst_Motors_7_6d0059adb8.webp" }
        ],
        "car_brand": "Lamborghini",

        "main_image": { link: 'small_WEBSITE_THUMBNAIL_aeb08164e7.jpg' }
    },
    {
        "title": "LaFerrari Aperta ",
        "description": "Maximum Power: 963 Horsepower,Maximum Torque: 900 Nm ,Maximum Speed: 350 KM/H ,0-100 Km/h (62mph): approximately 3.0 s ,0-200 Km/h (124mph): approximately 7.0 s ,Overall width: 1.992 m ,Overall length: 4.702 m, Height: 1.116 m, Wheelbase: 2.650 m",
        "year": 2016,
        "mileage": 0,
        "exterior_colour": "Red",
        "interior_colour": "Black ",
        "driver_position": "Rear Wheel Drive",
        "engine": "6.3L V-12 Naturally Aspirated Engine + eMotor",
        "body_type": "Hard Top Convertible ",
        "transmission": "7 Speed Automatic Transmission",
        "price": 0,
        "featured": true,
        "car_id": "FM-1030",
        "doors": 2,
        "power": 963,
        "torque": 900,
        "specification": "European",
        "top_speed": 350,
        "zero_to_100": 3.0,
        "more_info": "The LaFerrari Aperta stands at the pinnacle of automotive excellence, embodying the perfect fusion of speed, design, and open-top exhilaration. As a testament to Ferrari's commitment to pushing the boundaries of performance, the LaFerrari Aperta is a limited-edition marvel (210 units) that captures the essence of Italian luxury and precision engineering.",
        "ask_price": true,
        "images": [
            { link: "large_26_1795f8ef75.webp" },
            { link: "large_6_621888973e.webp" },
            { link: "large_5_9defd56078.webp" },
            { link: "large_11_118847eb61.webp" },
            { link: "large_1_cece5c285a.webp" },
            { link: "large_4_020149dd08.webp" },
            { link: "large_3_2334c797fb.webp" },
            { link: "large_7_64d0348037.webp" },
            { link: "large_2_f38c3edc61.webp" },
            { link: "large_8_e73368aba2.webp" },
            { link: "large_10_d47d995538.webp" },
            { link: "large_21_00c5ea5a05.webp" },
            { link: "large_23_a042169321.webp" },
            { link: "large_13_b76bdc6ca3.webp" },
            { link: "large_29_dba2a29bef.webp" },
            { link: "large_334_602e5e768e.webp" },
            { link: "large_38_376eb48b82.webp" },
            { link: "large_32_aa8a922484.webp" },
            { link: "large_34_87811fd2eb.webp" }
        ],
        "car_brand": "FERRARI",
        "main_image": { link: 'small_Speedtail_Thumb_594ef6652c.png' }
    },
    {
        "title": "Huayra Carbon Edition ",
        "description": "Maximum Power: 730 Horsepower",
        "year": 2014,
        "mileage": 0,
        "exterior_colour": "Black ",
        "interior_colour": "Red ",
        "driver_position": "Rear Wheel Drive",
        "engine": "6.0L V-12 Twin-Turbocharged Engine",
        "body_type": "Coupe ",
        "transmission": "7-Speed  Automatic Transmission",
        "price": 11500000,
        "featured": true,
        "car_id": "FM-1895",
        "doors": 2,
        "power": 730,
        "torque": 1000,
        "specification": "European ",
        "top_speed": 360,
        "zero_to_100": 3.3,
        "more_info": "The Pagani Huayra stands as a testament to the artistry and craftsmanship that can be achieved in the world of hypercars. Exuding an air of unparalleled exclusivity, this particular model boasts a unique distinction - it's the sole Pagani Huayra in the world featuring a full carbon fiber body, an accomplishment that places it in a league of its own.",
        "ask_price": false,
        "images": [
            { link: "large_yt_5ca4110866.jpg" },
            { link: "large_z_21d91f9764.jpg" },
            { link: "large_xx_917e9bd3dc.jpg" },
            { link: "large_xz_7616fdcfc9.jpg" },
            { link: "large_sss_750596e6d6.jpg" },
            { link: "large_az_343d9e2d8e.jpg" },
            { link: "large_zzzz_a258a89302.jpg" },
            { link: "large_s_396d4313c2.jpg" },
            { link: "large_Untitled_1_bad2de9ffc.jpg" },
            { link: "large_azaa_37bd1a5e26.jpg" },
            { link: "large_ju_c9e2500d71.jpg" },
            { link: "large_aaaa_8576078037.jpg" },
            { link: "large_wwee_b9afd09b82.jpg" },
            { link: "large_uu_b7c2a7428d.jpg" },
            { link: "large_gh_0e95ca6439.jpg" },
            { link: "large_bbb_84547c0b5d.jpg" },
            { link: "large_bbg_6a81759272.jpg" },
            { link: "large_bvvv_0ab1fc3b4e.jpg" },
            { link: "large_vfvv_658654be2e.jpg" },
            { link: "large_iuyy_10f8e169ec.jpg" }
        ],
        "car_brand": "Pagani",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_6eb4a2496d.jpg' }
    },
    {
        "title": "Chiron Super Sport 300+",
        "description": "Maximum Power: 1600 Horsepower",
        "year": 2022,
        "mileage": 600,
        "exterior_colour": "Black ",
        "interior_colour": "Black ",
        "driver_position": "All Wheel Drive",
        "engine": "8.0L W16 Quad-Turbocharged Engine",
        "body_type": "Coupe ",
        "transmission": "7 Speed Automatic Transmission",
        "price": 23499999,
        "featured": true,
        "car_id": "FM-1967",
        "doors": 2,
        "power": 1600,
        "torque": 1600,
        "specification": "EUROPEAN",
        "top_speed": 490,
        "zero_to_100": 2.4,
        "more_info": "Welcome to the realm of automotive hyperbole, where the laws of physics seem to bend and the very definition of speed takes on a new meaning. We stand before the Bugatti Chiron Super Sport 300+, a machine not merely an automobile, but a testament to the insatiable pursuit of automotive excellence.",
        "ask_price": false,
        "images": [
            { link: "large_1_18d34aed46.webp" },
            { link: "large_5_fb34a0bf3c.webp" },
            { link: "large_Untitled_1_8da7d7dc61.webp" },
            { link: "large_3_52c973c529.webp" },
            { link: "large_7_df2f88a5fb.webp" },
            { link: "large_11_bfe54c29d6.webp" },
            { link: "large_12_88f0ef7d37.webp" },
            { link: "large_23_8027dacb61.webp" },
            { link: "large_19_34f7d66cd7.webp" },
            { link: "large_10_f8de6b1cff.webp" },
            { link: "large_14_ef3854d1e0.webp" },
            { link: "large_20_b2879307a6.webp" },
            { link: "large_16_73a6cb386c.webp" },
            { link: "large_24_3223200154.webp" },
            { link: "large_25_36803de6b1.webp" },
            { link: "large_18_3cd55ee2b2.webp" },
            { link: "large_30_e69419d64a.webp" },
            { link: "large_31_6405dce1e4.webp" },
            { link: "large_27_dde74b1ac2.webp" }
        ],
        "car_brand": "Bugatti",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_c64e16710a.jpg' }
    },
    {
        "title": " 812 Competizione A",
        "description": "Maximum Power: 819 Horsepower",
        "year": 2023,
        "mileage": 0,
        "exterior_colour": "Yellow ",
        "interior_colour": "Black ",
        "driver_position": "Rear Wheel Drive",
        "engine": " 6.5L V12 Naturally Aspirated Engine",
        "body_type": "Hard Top Convertible ",
        "transmission": "7-Speed Automatic Transmission",
        "price": 9199999,
        "featured": true,
        "car_id": "FM-INV.PRGI-1002",
        "doors": 2,
        "power": 819,
        "torque": 692,
        "specification": "EUROPEAN",
        "top_speed": 340,
        "zero_to_100": 2.8,
        "more_info": "Unveiled in 2022, the 2023 Ferrari 812 Competizione A is a drop-top evolution of the already potent 812 Competizione, taking open-air motoring to a whole new level of performance and exhilaration. With its horse emblem proudly adorning the hood, the Competizione A is a rolling masterpiece.",
        "ask_price": false,
        "images": [
            { link: "large_12_ce82037af5.webp" },
            { link: "large_7_52167ea7b5.webp" },
            { link: "large_1_dcfff5637d.webp" },
            { link: "large_4_dc56306cbd.webp" },
            { link: "large_Untitled_1_36b0d55466.webp" },
            { link: "large_6_ebb26216ed.webp" },
            { link: "large_3_4c9577749e.webp" },
            { link: "large_9_f7b2e370c8.webp" },
            { link: "large_10_f8871a2791.webp" },
            { link: "large_20_c9b32af7ca.webp" },
            { link: "large_14_ea835e74ff.webp" },
            { link: "large_17_c4c5be63b1.webp" },
            { link: "large_15_23fdea8cd1.webp" },
            { link: "large_19_eb39b9e9dc.webp" },
            { link: "large_24_ffe9ffe518.webp" },
            { link: "large_27_8c95b8c45f.webp" },
            { link: "large_21_a2c5be4784.webp" },
            { link: "large_222_ebd61faf35.webp" },
            { link: "large_211_b091e245d5.webp" },
            { link: "large_29_c741fc5018.webp" }
        ],
        "car_brand": "FERRARI",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_1834a2579e.jpg' }
    },
    {
        "title": "918 Spyder Weissach ",
        "description": "Maximum Power: 887 Horsepower",
        "year": 2015,
        "mileage": 9875,
        "exterior_colour": "SILVER",
        "interior_colour": "BLACK",
        "driver_position": "All Wheel Drive",
        "engine": "4.6L V8 N/A Engine + eMotor",
        "body_type": "ROADSTER",
        "transmission": "7-Speed Automatic Transmission",
        "price": 6799999,
        "featured": true,
        "car_id": "FM-1866",
        "doors": 2,
        "power": 887,
        "torque": 1280,
        "specification": "EUROPEAN",
        "top_speed": 345,
        "zero_to_100": 2.6,
        "more_info": "The 2015 Porsche 918 Spyder with the Weissach Kit is an extraordinary and highly exclusive car, with only 918 units ever produced. This limited production run makes it a rare gem in the automotive world, coveted by collectors and enthusiasts worldwide.",
        "ask_price": false,
        "images": [
            { link: "large_13_e7d8551d07.jpg" },
            { link: "large_23_5a28d76c50.jpg" },
            { link: "large_8_3fdbd5103e.jpg" },
            { link: "large_14_42886f97d5.jpg" },
            { link: "large_11_b1490dcbe7.jpg" },
            { link: "large_15_fcccb02f25.jpg" },
            { link: "large_20_c20ccae83e.jpg" },
            { link: "large_9_8573c87dfd.jpg" },
            { link: "large_6_6ea130ede1.jpg" },
            { link: "large_12_55be0fce46.jpg" },
            { link: "large_22_d7fb45f645.jpg" },
            { link: "large_16_4a29432275.jpg" },
            { link: "large_21_00d3094484.jpg" },
            { link: "large_25_7e6ba4af35.jpg" },
            { link: "large_4_f7228327ee.jpg" },
            { link: "large_7_8f2ea24118.jpg" },
            { link: "large_1_0c8cd49ef5.jpg" },
            { link: "large_2_c76c0fc43b.jpg" },
            { link: "large_17_4627b23c8b.jpg" },
            { link: "large_26_d332f59d24.jpg" },
            { link: "large_3_8932963ed2.jpg" },
            { link: "large_10_0838f57cd1.jpg" },
            { link: "large_24_426c168264.jpg" },
            { link: "large_18_51d152ad8c.jpg" },
            { link: "large_5_89d19c4bcb.jpg" },
            { link: "large_19_0d93c787ab.jpg" }
        ],
        "car_brand": "PORSCHE",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_0b1adc320a.jpg' }
    },
    {
        "title": "918 Spyder Weissach Martini Edition",
        "description": "Maximum Power: 887 Horsepower",
        "year": 2015,
        "mileage": 6530,
        "exterior_colour": "WHITE , BLUE , RED",
        "interior_colour": "BLACK",
        "driver_position": "All Wheel Drive",
        "engine": "4.6L V8 N/A Engine + eMotor",
        "body_type": "ROADSTER",
        "transmission": "7-Speed Automatic Transmission",
        "price": 7299999,
        "featured": true,
        "car_id": "FM-1884",
        "doors": 2,
        "power": 887,
        "torque": 1280,
        "specification": "EUROPEAN",
        "top_speed": 345,
        "zero_to_100": 2.6,
        "more_info": "The Porsche 918 Spyder Weissach Martini Edition is a truly special and exclusive vehicle that combines the best of both worlds: the dynamic performance of the Weissach Kit and the iconic Martini Racing livery. The Weissach Kit, renowned for its exceptional engineering and track-focused enhancements, takes the Porsche 918 Spyder to new performance levels. It includes lightweight carbon fiber components, aerodynamic modifications, and optimized chassis settings. These features reduce the vehicle's weight and enhance its handling and agility, providing an exhilarating driving experience.",
        "ask_price": false,
        "images": [
            { link: "large_13_1434946817.jpg" },
            { link: "large_12_99b6581fac.jpg" },
            { link: "large_8_26a9a1430b.jpg" },
            { link: "large_7_6e8721e212.jpg" },
            { link: "large_10_b44244d19c.jpg" },
            { link: "large_21_bdd7528477.jpg" },
            { link: "large_14_35979d75a9.jpg" },
            { link: "large_15_a81bb91665.jpg" },
            { link: "large_20_0a52d47e50.jpg" },
            { link: "large_18_31b527fd2b.jpg" },
            { link: "large_19_2468791130.jpg" },
            { link: "large_17_5efa6373f1.jpg" },
            { link: "large_9_ec70de386f.jpg" },
            { link: "large_16_29d4978ae8.jpg" },
            { link: "large_6_959bee16a8.jpg" },
            { link: "large_5_c28c1b87d5.jpg" },
            { link: "large_11_aeb231de31.jpg" },
            { link: "large_3_fff1fcace7.jpg" },
            { link: "large_1_6e86607435.jpg" },
            { link: "large_4_649cdb2b0b.jpg" },
            { link: "large_2_fd33ea229c.jpg" }
        ],
        "car_brand": "PORSCHE",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_c6e9430fc8.jpg' }
    },
    {
        "title": "Senna ",
        "description": "Maximum Power: 789 Horsepower",
        "year": 2019,
        "mileage": 11353,
        "exterior_colour": "White ",
        "interior_colour": "Black ",
        "driver_position": "Rear Wheel Drive",
        "engine": "4.0L V-8 Twin-Turbocharged Engine",
        "body_type": "Coupe",
        "transmission": " 7 Speed Automatic Transmission",
        "price": 3399999,
        "featured": true,
        "car_id": "FM-INV.TM-1001",
        "doors": 2,
        "power": 789,
        "torque": 800,
        "specification": "GCC",
        "top_speed": 335,
        "zero_to_100": 2.8,
        "more_info": "The 2019 McLaren Senna is the epitome of automotive engineering, representing the pinnacle of track-focused road hypercars. With an unwavering commitment to performance, McLaren has crafted a masterpiece that pushes the boundaries and redefines them. This hypercar embodies the essence of speed and precision, setting new benchmarks with its extraordinary capabilities.",
        "ask_price": false,
        "images": [
            { link: "large_4_125a6e92ab.webp" },
            { link: "large_2_a21d2eb97a.webp" },
            { link: "large_1_Untitled_1_d6b1a0dbd2.webp" },
            { link: "large_11_9e53cb1e38.webp" },
            { link: "large_5_37343ceff1.webp" },
            { link: "large_6_6505e16b73.webp" },
            { link: "large_12_c0faf62608.webp" },
            { link: "large_3_ad2787ef1f.webp" },
            { link: "large_10_d630dc16e5.webp" },
            { link: "large_9_99d3697f6c.webp" },
            { link: "large_13_c33c8fab42.webp" },
            { link: "large_14_4001cc436c.webp" },
            { link: "large_16_e6abc4e35f.webp" },
            { link: "large_15_4db7721fe6.webp" },
            { link: "large_18_63254799b7.webp" },
            { link: "large_19_88a5fa3bf0.webp" },
            { link: "large_21_991d5db039.webp" },
            { link: "large_22_73fd9dbabf.webp" },
            { link: "large_20_d8e3822f23.webp" }
        ],
        "car_brand": "MCLAREN",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_3bc65b6f31.jpg' }
    },
    {
        "title": "Skyline GT-R 34 Series 1",
        "description": "Maximum Power: 276 Horsepower",
        "year": 1999,
        "mileage": 121439,
        "exterior_colour": "Black ",
        "interior_colour": "Grey",
        "driver_position": " 4 Wheel Drive",
        "engine": "2.6L I-6 Turbocharged Engine ",
        "body_type": "Coupe ",
        "transmission": "6-Speed Manual Transmission",
        "price": 949999,
        "featured": false,
        "car_id": "FM-INV.FC-1030",
        "doors": 2,
        "power": 276,
        "torque": 392,
        "specification": "Japanese ",
        "top_speed": 252,
        "zero_to_100": 5.4,
        "more_info": "The 1999 Skyline GT-R R34 is nothing short of a legend in the world of sports cars. It's a machine that continues to capture the hearts of enthusiasts worldwide, despite being a quarter of a century old. The R34 is a testament to both Nissan's engineering prowess and the enduring love for the automotive masterpiece it created.",
        "ask_price": false,
        "images": [
            { link: "large_NISSAN_GTR_0002_F1rst_Motors_21_dbdb3a5091.jpg" },
            { link: "large_NISSAN_GTR_0007_F1rst_Motors_16_1b19c8a4ca.jpg" },
            { link: "large_NISSAN_GTR_0008_F1rst_Motors_15_f6b640785c.jpg" },
            { link: "large_NISSAN_GTR_0009_F1rst_Motors_14_02ec89ee5f.jpg" },
            { link: "large_NISSAN_GTR_0001_F1rst_Motors_22_1db34f3dcb.jpg" },
            { link: "large_NISSAN_GTR_0000_F1rst_Motors_23_3860364747.jpg" },
            { link: "large_NISSAN_GTR_0003_F1rst_Motors_20_fb4763fdd4.jpg" },
            { link: "large_NISSAN_GTR_0004_F1rst_Motors_19_893caa7605.jpg" },
            { link: "large_NISSAN_GTR_0005_F1rst_Motors_18_d7ca513700.jpg" },
            { link: "large_NISSAN_GTR_0006_F1rst_Motors_17_8a75419e0d.jpg" },
            { link: "large_NISSAN_GTR_0014_F1rst_Motors_9_e6c315ccdd.jpg" },
            { link: "large_NISSAN_GTR_0010_F1rst_Motors_13_81e6e1be35.jpg" },
            { link: "large_NISSAN_GTR_0012_F1rst_Motors_11_f63cd7f248.jpg" },
            { link: "large_NISSAN_GTR_0011_F1rst_Motors_12_05f164a6dd.jpg" },
            { link: "large_NISSAN_GTR_0013_F1rst_Motors_10_f33a219e8d.jpg" },
            { link: "large_NISSAN_GTR_0017_F1rst_Motors_6_d7307d24ec.jpg" },
            { link: "large_NISSAN_GTR_0018_F1rst_Motors_5_884c604d3a.jpg" },
            { link: "large_NISSAN_GTR_0016_F1rst_Motors_7_e288eae107.jpg" },
            { link: "large_NISSAN_GTR_0015_F1rst_Motors_8_c4d10b7280.jpg" }
        ],
        "car_brand": "Nissan",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_1_b169326e96.jpg' }
    },
    {
        "title": "812 GTS ",
        "description": "Maximum Power: 789 Horsepower",
        "year": 2022,
        "mileage": 450,
        "exterior_colour": "Blue ",
        "interior_colour": "Black ",
        "driver_position": "Rear Wheel Drive",
        "engine": "6.5L V12 Naturally Aspirated Engine",
        "body_type": "Hard Top Convertible ",
        "transmission": "7-Speed Automatic Transmission",
        "price": 2050000,
        "featured": true,
        "car_id": "FM-1928",
        "doors": 2,
        "power": 789,
        "torque": 720,
        "specification": "EUROPEAN",
        "top_speed": 340,
        "zero_to_100": 2.9,
        "more_info": "The 2022 Ferrari 812 GTS is a stunning convertible supercar that effortlessly combines style, luxury, and cutting-edge technology. The car is all about providing an extraordinary driving experience while offering the comfort and convenience you'd expect from a high-end vehicle.",
        "ask_price": false,
        "images": [
            { link: "large_gts_blue_0007_F1rst_Motors_17_9822180fbf.jpg" },
            { link: "large_gts_blue_0010_F1rst_Motors_14_0503fb255d.jpg" },
            { link: "large_gts_blue_0000_F1rst_Motors_24_01eb37e5d4.jpg" },
            { link: "large_gts_blue_0001_F1rst_Motors_23_89b57d4275.jpg" },
            { link: "large_gts_blue_0002_F1rst_Motors_22_517aad538a.jpg" },
            { link: "large_gts_blue_0003_F1rst_Motors_21_6794bec74f.jpg" },
            { link: "large_gts_blue_0004_F1rst_Motors_20_00a1842f64.jpg" },
            { link: "large_gts_blue_0005_F1rst_Motors_19_b425cc32ad.jpg" },
            { link: "large_gts_blue_0014_F1rst_Motors_10_77fe3deb99.jpg" },
            { link: "large_gts_blue_0009_F1rst_Motors_15_d2d7d815fe.jpg" },
            { link: "large_gts_blue_0006_F1rst_Motors_18_4d19c6d095.jpg" },
            { link: "large_gts_blue_0011_F1rst_Motors_13_d964f96b8b.jpg" },
            { link: "large_gts_blue_0013_F1rst_Motors_11_3c0d9bc12f.jpg" },
            { link: "large_gts_blue_0008_F1rst_Motors_16_01fe7c9fbb.jpg" },
            { link: "large_gts_blue_0012_F1rst_Motors_12_e59f322c1a.jpg" },
            { link: "large_gts_blue_0017_F1rst_Motors_6_ed6697c802.jpg" },
            { link: "large_gts_blue_0018_F1rst_Motors_5_7ab062fa2e.jpg" },
            { link: "large_gts_blue_0016_F1rst_Motors_8_4a1926ce39.jpg" },
            { link: "large_gts_blue_0015_F1rst_Motors_9_0ece777154.jpg" }
        ],
        "car_brand": "FERRARI",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_7e25d6bf96.jpg' }
    },
    {
        "title": "Urus P745 Venatus by Mansory",
        "description": "Maximum Power: 745 Horsepower",
        "year": 2022,
        "mileage": 15841,
        "exterior_colour": "White ",
        "interior_colour": "Red ",
        "driver_position": "All Wheel Drive",
        "engine": "4.0L V8 Twin-Turbocharged Engine",
        "body_type": "SUV ",
        "transmission": "8 Speed Automatic Transmission",
        "price": 1420000,
        "featured": false,
        "car_id": "FM-1964",
        "doors": 4,
        "power": 745,
        "torque": 960,
        "specification": "EUROPEAN",
        "top_speed": 320,
        "zero_to_100": 0,
        "more_info": "The Urus P745 Venatus by Mansory is a high-performance, wide-body version of the Lamborghini Urus, created by the tuning house Mansory. ",
        "ask_price": false,
        "images": [
            { link: "large_13_ccacc2e86a.webp" },
            { link: "large_6_1f79660ff4.webp" },
            { link: "large_1_99136790de.webp" },
            { link: "large_4_d32c773d26.webp" },
            { link: "large_2_f85fd90358.webp" },
            { link: "large_7_835b21ea59.webp" },
            { link: "large_5_87c28f1eac.webp" },
            { link: "large_3_aec5efebe4.webp" },
            { link: "large_10_02f80103c9.webp" },
            { link: "large_11_43d037b35e.webp" },
            { link: "large_18_d28c93339a.webp" },
            { link: "large_20_7394284065.webp" },
            { link: "large_12_a107810a0e.webp" },
            { link: "large_14_2febc457ed.webp" },
            { link: "large_17_9cf25fe974.webp" },
            { link: "large_16_8194e6dda9.webp" },
            { link: "large_25_0aaf22d4b9.webp" },
            { link: "large_21_4a92fe7f0c.webp" },
            { link: "large_22_402d61b816.webp" },
            { link: "large_24_e05f8fc7db.webp" },
            { link: "large_31_beed22ad83.webp" },
            { link: "large_34_b8c46d746c.webp" },
            { link: "large_30_80003b26d5.webp" },
            { link: "large_27_cb6027d8a4.webp" }
        ],
        "car_brand": "Lamborghini",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_b096e8da95.jpg' }
    },
    {
        "title": "918 Spyder with Weissach Kit",
        "description": "Maximum Power: 887 Horsepower",
        "year": 2015,
        "mileage": 8518,
        "exterior_colour": "Silver",
        "interior_colour": "Black",
        "driver_position": "All Wheel Drive",
        "engine": "4.6L V8 N/A Engine + eMotor",
        "body_type": "ROADSTER",
        "transmission": "7-Speed Automatic Transmission",
        "price": 6299999,
        "featured": true,
        "car_id": "FM-INV.LE-1001",
        "doors": 2,
        "power": 887,
        "torque": 1280,
        "specification": "GCC",
        "top_speed": 345,
        "zero_to_100": 2.6,
        "more_info": "The 2015 Porsche 918 Spyder with the Weissach Kit is an extraordinary and highly exclusive car, with only 918 units ever produced. This limited production run makes it a rare gem in the automotive world, coveted by collectors and enthusiasts worldwide.",
        "ask_price": false,
        "images": [
            { link: "large_30_87bfcab5d3.jpg" },
            { link: "large_29_f20f92c686.jpg" },
            { link: "large_18_8d13c9494a.jpg" },
            { link: "large_28_1bda5734fc.jpg" },
            { link: "large_10_51bbcc5219.jpg" },
            { link: "large_24_79ac25ac7f.jpg" },
            { link: "large_7_e2b8054b51.jpg" },
            { link: "large_17_29458f0fc7.jpg" },
            { link: "large_23_e853c5377d.jpg" },
            { link: "large_15_50aeeb29db.jpg" },
            { link: "large_25_c99bfe4955.jpg" },
            { link: "large_31_70e216d900.jpg" },
            { link: "large_11_63635ac6ff.jpg" },
            { link: "large_8_4d85da9832.jpg" },
            { link: "large_6_90b8c8dbc9.jpg" },
            { link: "large_12_a7518e053f.jpg" },
            { link: "large_5_f72616c401.jpg" },
            { link: "large_14_4b5b48e857.jpg" },
            { link: "large_13_31169ee5cc.jpg" },
            { link: "large_9_00dbd7d71c.jpg" },
            { link: "large_16_398962c254.jpg" },
            { link: "large_26_f5dd12d6ac.jpg" },
            { link: "large_27_41578ff0e2.jpg" },
            { link: "large_19_17debc9214.jpg" },
            { link: "large_20_dcceec57fb.jpg" },
            { link: "large_21_c3696087dd.jpg" },
            { link: "large_22_dde9e1abd9.jpg" }
        ],
        "car_brand": "PORSCHE",
        "main_image": { link: 'small_website1_b3d11cec02.jpg' }
    },
    {
        "title": "SF90 Spider Assetto Fiorano Package ",
        "description": "Maximum Power: 986 Horsepower",
        "year": 2022,
        "mileage": 0,
        "exterior_colour": "Yellow ",
        "interior_colour": "Black ",
        "driver_position": "",
        "engine": "4.0L V8 Twin-Turbocharged Engine + eMotor",
        "body_type": "Hard Top Convertible ",
        "transmission": " 8 Speed Dual-Clutch Automatic Transmission",
        "price": 2699999,
        "featured": false,
        "car_id": "FM- 1955 ",
        "doors": 2,
        "power": 986,
        "torque": 800,
        "specification": "EUROPEAN",
        "top_speed": 340,
        "zero_to_100": 2.5,
        "more_info": "The 2022 Ferrari SF90 Stradale Assetto Fiorano is a high-performance plug-in hybrid supercar that was first introduced in 2019. It is the most powerful Ferrari road car ever produced, with a combined output of 986 horsepower. The Assetto Fiorano package adds a number of track-focused upgrades, including stiffer suspension, lighter wheels, and downforce-enhancing aero components.",
        "ask_price": false,
        "images": [
            { link: "large_12_53e632ece5.webp" },
            { link: "large_1_e99cf24696.webp" },
            { link: "large_7_382cf5bc88.webp" },
            { link: "large_2_4d3153cb1b.webp" },
            { link: "large_3_f435090817.webp" },
            { link: "large_5_68c952f16d.webp" },
            { link: "large_6_b19437962d.webp" },
            { link: "large_8_411bd161ad.webp" },
            { link: "large_9_e63d938bc2.webp" },
            { link: "large_10_4434887d61.webp" },
            { link: "large_11_936cd96c26.webp" },
            { link: "large_16_e7fb859c9e.webp" },
            { link: "large_14_911bfbde5e.webp" },
            { link: "large_17_3ff72d6078.webp" },
            { link: "large_19_9c323b7824.webp" },
            { link: "large_20_12d3b99e64.webp" },
            { link: "large_21_0f4055c4e2.webp" },
            { link: "large_23_44856dbcfa.webp" },
            { link: "large_24_22fb7d7f1f.webp" },
            { link: "large_22_c93d558aa0.webp" }
        ],
        "car_brand": "FERRARI",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_8102451d43.jpg' }
    },
    {
        "title": "Urus Performante",
        "description": "Maximum Speed: 306 KM/H",
        "year": 2024,
        "mileage": 0,
        "exterior_colour": "Nero Helene",
        "interior_colour": "Black ",
        "driver_position": "All Wheel Drive",
        "engine": " 4.0L V8 Twin-Turbocharged Engine",
        "body_type": "SUV ",
        "transmission": "8 Speed Automatic Transmission",
        "price": 1599999,
        "featured": false,
        "car_id": "FM 1934",
        "doors": 4,
        "power": 666,
        "torque": 850,
        "specification": "EUROPEAN",
        "top_speed": 306,
        "zero_to_100": 3.3,
        "more_info": "Introducing the 2024 Lamborghini Urus Performante, a revolutionary leap forward in Super Sport Utility Vehicles. This visionary concept represents the pinnacle of SUV performance, setting a new standard for driving enthusiasts. Fresh to the scene, the 2024 model is the epitome of cutting-edge design and innovation, redefining the boundaries of high-performance SUVs.",
        "ask_price": false,
        "images": [
            { link: "large_11_39279f304c.webp" },
            { link: "large_4_9b4065bcae.webp" },
            { link: "large_20_604ca57e0b.webp" },
            { link: "large_5_3162004caa.webp" },
            { link: "large_7_ff45dd4fff.webp" },
            { link: "large_Untitled_1_bae16a8c5a.webp" },
            { link: "large_2_9e1a2336f0.webp" },
            { link: "large_3_8e0086fd94.webp" },
            { link: "large_8_64bdebc647.webp" },
            { link: "large_10_385529ecd5.webp" },
            { link: "large_6_c3fca6a880.webp" },
            { link: "large_14_8f8cac48fe.webp" },
            { link: "large_16_165218ffd7.webp" },
            { link: "large_13_9b0f1fe6ca.webp" },
            { link: "large_178webp_9f6c9a812f.webp" },
            { link: "large_17_9d8fc0175f.webp" },
            { link: "large_19_1f1abaa5e1.webp" },
            { link: "large_21_a567110ce1.webp" },
            { link: "large_24_5a8568c02a.webp" },
            { link: "large_25_afdc31ecbc.webp" },
            { link: "large_23_df1eb3ac75.webp" },
            { link: "large_22_c673e3ad29.webp" }
        ],
        "car_brand": "Lamborghini",
        "main_image": { link: 'small_WEBSITE_THUMBNAIL_13e9005cc0.jpg' }
    }
]
export default cars_records;
